# This is a basic workflow to help you get started with Actions
name: Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
      - v*

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #   check:
  #     runs-on: ubuntu-latest
  #     outputs:
  #       branch: ${{ steps.check_step.outputs.branch }}
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 0

  #       - name: Get current branch
  #         id: check_step
  #         run: |
  #           raw=$(git branch -r --contains ${{ github.ref }})
  #           branch=${raw##*/}
  #           echo "::set-output name=branch::$branch"
  #           echo "Branch is $branch."

  # This workflow contains a single job called "build"
  build:
    # if: ${{ needs.check.outputs.branch == 'master' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ github.event.ref != 'master' }}
          echo ${{ github.event.ref_type }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
